Book
VasylAzarov/springproject pull request #1
Opened 2024-12-03 09:45 UTC by VasylAzarov

Added and installed base dependencies.
Added main Application class and main test MateApplicationTests class.
Set properties and test properties, added properties files.
Added and set ci file.
Added Book entity, Book Service, Book Repo classes.

2024-12-03 12:05 UTC, Elena-Bruyako requested changes
see comments

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/Application.java
> +    }
implement
Class with `@SpringBootApplication` annotation that will have a CommandLineRunner bean.
where you should call all methods from BookService

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/model/Book.java
> +@Entity(name = "book")
```suggestion
@Entity
@Table(name = "books")
@Getter
@Setter
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/model/Book.java
> +    private long id;
```suggestion
    private Long id;
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/model/Book.java
> +    public Book() {
remove all code below this line

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/model/Book.java
> +    private String title;
add required constraints 

```
id (Long, PK)
title (String, not null)
author (String, not null)
isbn (String, not null, unique)
price (BigDecimal, not null)
description (String)
coverImage (String)
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/repository/BookRepository.java
> +
remove empty line after class declaration

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/repository/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/repository/BookRepositoryImpl.java
> +    private SessionFactory sessionFactory;
```suggestion
    private final SessionFactory sessionFactory;
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/repository/BookRepositoryImpl.java
> +        Session session = sessionFactory.getCurrentSession();
please, refresh your knowledge about JDBC and fix save and findAll methods

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/repository/BookRepositoryImpl.java
> +        HibernateCriteriaBuilder builder = session.getCriteriaBuilder();
you don't need CriteriaBuilder here

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/main/java/com/example/mate/service/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on src/test/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
```suggestion
```

2024-12-03 12:05 UTC, Elena-Bruyako commented on pom.xml
> +        <version>3.1.1</version> <!-- Используйте последнюю версию -->
remove comments in pom file

2024-12-03 19:08 UTC, okuzan requested changes

2024-12-03 19:08 UTC, okuzan commented on src/main/java/com/example/model/Book.java
> +@ToString
```suggestion
@ToString
```
ok here, but be careful with ToString on JPA entities - can cause LazyInitEx if you had other entities as fields here

2024-12-03 19:08 UTC, okuzan commented on src/test/java/com/example/MateApplicationTests.java
> +public class MateApplicationTests {
Don't use `Mate` in this project, it will go to your portfolio. Rename this repo too. Also rename com.example to smth more relevant

2024-12-03 19:08 UTC, okuzan commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/mate_db
mate again

2024-12-03 19:08 UTC, okuzan commented on src/main/java/com/example/repository/BookRepositoryImpl.java
> +    }
here we are supposed to use explicit transaction management approach using Hibernate's Session and Transaction

2024-12-04 07:39 UTC, liliia-ponomarenko approved these changes
Good job! But fix my comments before merging ;)

2024-12-04 07:39 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/Application.java
> +@EntityScan(basePackages = "dev.vasyl.proj")
Do you really  need it?

2024-12-04 07:39 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/model/Book.java
> +@Table(name = "book")
```suggestion
@Table(name = "books")
```

2024-12-04 09:46 UTC, merged