Spring Boot practice
VasylAzarov/springproject pull request #10
Opened 2024-12-11 16:20 UTC by VasylAzarov

add category entity | now books has category set | add category endpoints and documentation | add category mapper | update book entity, service, repo, mapper, controller | add new db scripts

2024-12-11 19:50 UTC, Elena-Bruyako requested changes
see comments

2024-12-11 19:50 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/dto/book/CreateBookRequestDto.java
> +    private List<Long> categoryIds;
```suggestion
    @NotEmpty
    private List<Long> categoryIds;
```

2024-12-11 19:50 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(updatedCategory);
```suggestion
        categoryRepository.save(existingCategory);
        return categoryMapper.toDto(existingCategory);
```

2024-12-12 11:29 UTC, JJJazl approved these changes

2024-12-12 11:29 UTC, JJJazl commented on src/main/java/dev/vasyl/proj/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid CreateCategoryRequestDto requestDto) {
Let's add a corresponding status code for POST method

2024-12-12 11:29 UTC, JJJazl commented on src/main/java/dev/vasyl/proj/repository/BookRepository.java
> +    Page<Book> findByCategoriesId(Long categoryId, Pageable pageable);
```suggestion
    Page<Book> findByCategoryId(Long categoryId, Pageable pageable);
```

2024-12-12 15:12 UTC, merged