Spring boot practice 2
VasylAzarov/springproject pull request #11
Opened 2024-12-12 15:13 UTC by VasylAzarov

Implemented cat logic with entities, service, repository,mapper, controller, dtos | implemented endpoints for getting cart, adding to cart, updating cart, deleting from cart

2024-12-12 17:40 UTC, Elena-Bruyako requested changes
see comments

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/controller/ShoppingCartController.java
> +    public CartItemDto addItem(@AuthenticationPrincipal User user,
```suggestion
    public CartResponseDto addItem(@AuthenticationPrincipal User user,
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/controller/ShoppingCartController.java
> +    public CartItemDto updateItem(@PathVariable Long cartItemId,
```suggestion
    public CartResponseDto updateItem(@PathVariable Long cartItemId,
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/dto/shopping/cart/CreateCartItemRequestDto.java
> +        @Min(0)
```suggestion
        @Positive
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/dto/shopping/cart/UpdateCartItemRequestDto.java
> +        @Min(0)
```suggestion
        @Positive
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/model/ShoppingCart.java
> +    @OneToOne
you can use `@MapsId` here

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/service/impl/CartManagementServiceImpl.java
> +public class CartManagementServiceImpl implements CartManagementService {
```suggestion
public class ShoppingCartServiceImpl implements CartManagementService {
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/service/CartManagementService.java
> +public interface CartManagementService {
```suggestion
public interface ShoppingCartService {
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/service/impl/CartManagementServiceImpl.java
> +    public Page<CartItemDto> findAll(User user, Pageable pageable) {
```suggestion
    public Page< CartResponseDto > findAll(User user, Pageable pageable) {
```

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/service/impl/CartManagementServiceImpl.java
> +@Service
Think where is `@Transactional` needed

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/service/impl/UserServiceImpl.java
> +    private void createShoppingCartForUser(User user) {
replace this method to ShopCartService

2024-12-12 17:40 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/10-create-shoping_carts-table.yaml
```suggestion
      file: db/changelog/changes/10-create-shopping_carts-table.yaml
```

2024-12-13 07:01 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few comments ;)

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/mapper/ShoppingCartMapper.java
> +                : new PageImpl<>(dtoList, PageRequest.of(0, dtoList.size()), dtoList.size());
you can use the method map of Page and simplify this method

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/mapper/ShoppingCartMapper.java
> +    }
the same

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/repository/ShoppingCartRepository.java
> +
```suggestion
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
    Optional<ShoppingCart> findByUserId(Long userId);
```

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/service/impl/ShoppingCartServiceImpl.java
> +        return cartItemSet.stream()
better return Optional instead  of null and use Optional methods for conditional

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/service/impl/ShoppingCartServiceImpl.java
> +        }
Better throw some Exception and return 4xx response

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/service/impl/ShoppingCartServiceImpl.java
> +    public void createShoppingCartForUser(User user) {
move it before private methods. Override annotation missed

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/java/dev/vasyl/proj/service/impl/UserServiceImpl.java
> +    }
Should you use Transactional here?

2024-12-13 07:01 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/10-create-shoping-carts-table.yaml
```suggestion
      file: db/changelog/changes/10-create-shopping-carts-table.yaml
```

2024-12-13 11:09 UTC, Elena-Bruyako requested changes
see comments

2024-12-13 11:09 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/controller/ShoppingCartController.java
> +    public CartItemResponseDto addItem(@AuthenticationPrincipal User user,
```suggestion
    public CartResponseDto addItem(@AuthenticationPrincipal User user,
```

2024-12-13 11:09 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/controller/ShoppingCartController.java
> +    public CartItemResponseDto updateItem(@PathVariable Long cartItemId,
```suggestion
    public CartResponseDto updateItem(@PathVariable Long cartItemId,
```

2024-12-13 14:11 UTC, JJJazl approved these changes

2024-12-13 14:11 UTC, JJJazl commented on src/main/java/dev/vasyl/proj/model/ShoppingCart.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-12-13 14:11 UTC, JJJazl commented on src/main/java/dev/vasyl/proj/service/impl/ShoppingCartServiceImpl.java
> +    @Transactional
You can move `@Transactional` above the class
Maybe this article will help you better understand how these annotations and pattern Proxy work:
https://medium.com/@denis.verkhovsky/spring-how-annotations-work-part-2-f9ea764abc28

2024-12-13 14:11 UTC, JJJazl commented on src/main/java/dev/vasyl/proj/service/impl/UserServiceImpl.java
> +        User user = saveUser(userMapper.toModel(requestDto),
Add `@Transactional` above the class

2024-12-13 14:28 UTC, merged