implemented Book RestController logic + DTO + mapstruct
VasylAzarov/springproject pull request #2
Opened 2024-12-04 15:22 UTC by VasylAzarov

added mapstruct lib and plugin | added BookController, BookDto, BookMapper, CreateBookRequestDto, EntityNotFoundException, MapperConfig classes | implemented controller, service and dto logic for Book entity | removed CommandLineRunner | updated Application, BookRepository, BookRepositoryImpl, BookService, BookServiceImpl, pom.xml

2024-12-04 15:55 UTC, Elena-Bruyako requested changes
see comments

2024-12-04 15:55 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/mapper/BookMapper.java
> +    Book toModel(CreateBookRequestDto createBookRequestDto);
do you really need all this methods?

2024-12-04 15:55 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/repository/BookRepositoryImpl.java
> +        try {
use try with resources with session here

2024-12-04 15:55 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/service/BookServiceImpl.java
> +                () -> new RuntimeException("Can`t find Book entity bi id: " + id));
```suggestion
                () -> new EntityNotFoundException("Can`t find Book entity by id: " + id));
```

2024-12-04 15:55 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Failed to find entity by id: " + id, e);
```suggestion
            throw new DataProcessingException("Failed to find entity by id: " + id, e);
```

2024-12-04 15:55 UTC, Elena-Bruyako commented on src/main/java/dev/vasyl/proj/repository/BookRepositoryImpl.java
>          try {
same here - try with resources and DataProcessingException

2024-12-04 18:29 UTC, okuzan commented on src/main/java/dev/vasyl/proj/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Failed to find entity by id: " + id, e);
not fixed

2024-12-04 18:30 UTC, okuzan requested changes
Don't use generic exceptions like Runtime

2024-12-04 18:30 UTC, okuzan commented on src/main/java/dev/vasyl/proj/service/BookServiceImpl.java
> +                .toList();
FYI if you want you can declare mapping List to List in mapstruct interface instead of stream map

2024-12-05 07:13 UTC, liliia-ponomarenko approved these changes
Good job!

2024-12-05 09:59 UTC, merged